### ISSUE TITLE
WAI Website resource / repo structure

### ISSUE THREAD

**Issue by SteveALee** [w3c/wai-interactive-lists#7]
Things to check about `wai-course-list with @leticiaseixas

- [x] aren't `/index .md` & `/submit-an-offer .md` just junk? They are also in `/content/` where both have same permalink which is bad.
- [x] `repository` in front matter should be w3c now
- [x] need to set `redirects` in `netlify.toml` so previews work correctly

Things for Steve to check 

- [x] why `.github/workflows/init.yml` as the created links should be static and commited?
- [x] is `.github/workflows/makesite.yml` actually used as it seems to be pointless?
- [x] use of ref vs permalink to specify URI?
- [x] assets in `_include` rather than `_assets` is OK?
- [x] Can we improve local dev to autobuild changes?
- [x] liquid files in include?
- [ ] ref: /teach-advocate/course-list/,  changelog: /teach-advocate/course-list/changelog/  acknowledgements: /teach-advocate/course-list/acknowledgements/

**Comment by leticiaseixas** [comment]
> Things to check about `wai-course-list with @leticiaseixas
> 
> * [ ]  aren't `/index .md` & `/submit-an-offer .md` just junk? They are also in `/content/` where both have same permalink which is bad.
- yes, fixed
> * [ ]  `repository` in front matter should be w3c now
- fixed
> * [ ]  need to set `redirects` in `netlify.toml` so previews work correctly
- fixed

**Comment by SteveALee** [comment]
@leticiaseixas thanks for the update. I checked them above

**Comment by SteveALee** [comment]
> why .github/workflows/init.yml as the created links should be static and commited?
> is .github/workflows/makesite.yml actually used as it seems to be pointless?

neither needed

>  use of ref vs permalink to specify URI?

Looks like `ref` is used in translations - permalink is as usual

> assets in _include rather than _assets is OK?

They ARE included and so are in the right place
